// Generated by CoffeeScript 1.8.0
(function() {
  module.exports = function(grunt) {
    var bootstrapFolder, jQueryFolder, publicFolder;
    bootstrapFolder = 'bower_components/bootstrap/dist/';
    jQueryFolder = 'bower_components/jquery/dist/';
    publicFolder = 'public/lib/';
    grunt.initConfig({
      copy: {
        main: {
          files: [
            {
              cwd: bootstrapFolder + 'js/',
              expand: true,
              src: '*.min.js',
              dest: publicFolder + 'scripts/'
            }, {
              cwd: bootstrapFolder + 'css/',
              expand: true,
              src: '*.min.css',
              dest: publicFolder + 'stylesheets/'
            }, {
              cwd: bootstrapFolder + 'fonts/',
              expand: true,
              src: '*',
              dest: publicFolder + 'fonts/'
            }, {
              cwd: jQueryFolder,
              expand: true,
              src: '*.min.js',
              dest: publicFolder + 'scripts/'
            }
          ]
        }
      }
    });
    grunt.loadNpmTasks('grunt-contrib-copy');
    return grunt.registerTask('default', ['copy']);
  };

}).call(this);

//# sourceMappingURL=Gruntfile.js.map
