// Generated by CoffeeScript 1.8.0
(function() {
  var app, connect, http, morgan, serve, serveStatic;

  connect = require('connect');

  http = require('http');

  morgan = require('morgan');

  serveStatic = require('serve-static');

  serve = serveStatic('public');

  app = connect().use(morgan('combined')).use(serve);

  http.createServer(app).listen(80);

}).call(this);

//# sourceMappingURL=index.js.map
